import { FormEvent, useEffect, useState } from 'react';
import { Plus, RadioTower, ShieldCheck } from 'lucide-react';
import { api } from '../api/client';
const empty={name:'',code:'',newPrefix:'',color:'#6E3482',status:'active',notes:''};
export default function Operators(){
 const [items,setItems]=useState<any[]>([]);const[form,setForm]=useState<any>(empty);const[message,setMessage]=useState('');const[saving,setSaving]=useState(false);
 const load=()=>api<any>('/operators').then(r=>setItems(r.data));useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMessage('');try{await api('/operators',{method:'POST',body:JSON.stringify(form)});setForm(empty);setMessage('Operator created successfully. Add verified migration rules before publishing.');await load();}catch(e:any){setMessage(e.message)}finally{setSaving(false)}}
 async function disable(id:string){try{await api('/operators/'+id,{method:'DELETE'});setMessage('Operator disabled. Publish rules if mobile devices must receive this change.');await load();}catch(e:any){setMessage(e.message)}}
 return <div className="adminPage"><div className="topbar"><div className="pageTitle"><span className="eyebrow">NETWORK CONFIGURATION</span><h1>Operators</h1><p>Manage official mobile operators and their assigned two-digit migration prefixes.</p></div><span className="contextBadge"><RadioTower size={17}/>{items.filter(x=>x.status==='active').length} active</span></div>{message&&<p className="notice">{message}</p>}
 <div className="contentSplit"><form className="card formCard" onSubmit={submit}><div className="cardHeader"><div className="cardIcon"><Plus size={20}/></div><div><h2>Add operator</h2><p>Create only from verified regulatory information.</p></div></div><div className="formGrid"><label>Operator name<input className="input" required placeholder="e.g. QCell" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Operator code<input className="input" required placeholder="e.g. QCELL" value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></label><label>New prefix<input className="input" required inputMode="numeric" maxLength={2} placeholder="2 digits" value={form.newPrefix} onChange={e=>setForm({...form,newPrefix:e.target.value.replace(/\D/g,'')})}/></label><label>Brand colour<div className="colorField"><input type="color" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/><input className="input" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></div></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="disabled">Disabled</option></select></label><label className="wideField">Official source notes<textarea rows={4} required placeholder="PURA letter reference and effective date" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><button className="btn" disabled={saving}>{saving?'Saving…':'Save operator'}</button></form>
 <aside className="card infoCard"><div className="cardIcon"><ShieldCheck size={21}/></div><h2>Production safeguard</h2><p>An operator alone does not migrate contacts. A verified active rule must be tested and published before it reaches phones.</p><div className="miniFacts"><span><b>Prefix format</b><small>Exactly 2 digits</small></span><span><b>Source</b><small>PURA-approved allocation</small></span><span><b>Publishing</b><small>Controlled in Migration Rules</small></span></div></aside></div>
 <section className="card dataCard"><div className="cardHeader"><div><h2>Configured operators</h2><p>{items.length} operator record{items.length===1?'':'s'} in the system.</p></div></div><div className="tableWrap"><table><thead><tr><th>Operator</th><th>Code</th><th>New prefix</th><th>Official note</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(o=><tr key={o.id}><td><div className="operatorName"><span style={{background:o.color||'#6E3482'}}/><strong>{o.name}</strong></div></td><td><code>{o.code}</code></td><td><strong className="prefixValue">{o.newPrefix}</strong></td><td><span className="tableDescription">{o.notes||'No source note'}</span></td><td><span className={`statusBadge ${o.status}`}>{o.status}</span></td><td><button className="btn danger compact" disabled={o.status!=='active'} onClick={()=>disable(o.id)}>Disable</button></td></tr>)}</tbody></table></div>{!items.length&&<div className="emptyState"><RadioTower size={28}/><b>No operators configured</b><span>Add the first verified operator above.</span></div>}</section></div>;
}
