import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api } from '../api/client';

type RuleType = 'prefix' | 'range' | 'exact' | 'exception';
type RuleForm = { operatorId:string; ruleName:string; ruleType:RuleType; prefixValue:string; rangeFrom:string; rangeTo:string; exactNumber:string; newPrefix:string; priority:number|string; status:'active'|'inactive'; notes:string };
const emptyForm: RuleForm = { operatorId:'', ruleName:'', ruleType:'prefix', prefixValue:'', rangeFrom:'', rangeTo:'', exactNumber:'', newPrefix:'', priority:100, status:'active', notes:'' };

function valueFor(rule:any) { if (rule.ruleType === 'prefix') return rule.prefixValue || '—'; if (rule.ruleType === 'range') return `${rule.rangeFrom || '?'} – ${rule.rangeTo || '?'}`; if (rule.ruleType === 'exact') return rule.exactNumber || '—'; return rule.exactNumber || rule.prefixValue || `${rule.rangeFrom || '?'} – ${rule.rangeTo || '?'}`; }
function payload(form:RuleForm) { return { ...form, priority:Number(form.priority), prefixValue:form.prefixValue.trim()||null, rangeFrom:form.rangeFrom.trim()||null, rangeTo:form.rangeTo.trim()||null, exactNumber:form.exactNumber.trim()||null, ruleName:form.ruleName.trim(), notes:form.notes.trim()||null }; }

export default function Rules() {
  const [rules,setRules]=useState<any[]>([]); const [operators,setOperators]=useState<any[]>([]); const [status,setStatus]=useState<any>(null);
  const [test,setTest]=useState('3451567'); const [testResult,setTestResult]=useState<any>(null); const [message,setMessage]=useState<{text:string;error?:boolean}|null>(null);
  const [form,setForm]=useState<RuleForm>(emptyForm); const [editingId,setEditingId]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [publishing,setPublishing]=useState(false); const [testing,setTesting]=useState(false);
  const activeOperators=useMemo(()=>operators.filter((o)=>o.status==='active'),[operators]);

  async function load() {
    setLoading(true);
    try {
      const [ruleRes,opRes,statusRes]=await Promise.all([api<any>('/admin/migration-rules'),api<any>('/operators'),api<any>('/admin/migration-rules/status')]);
      setRules(ruleRes.data||[]); setOperators(opRes.data||[]); setStatus(statusRes.data);
      setForm((current)=>{ if(current.operatorId) return current; const op=(opRes.data||[]).find((x:any)=>x.status==='active'); return op?{...current,operatorId:op.id,newPrefix:op.newPrefix}:current; });
    } catch(err:any) { setMessage({text:err.message||'Could not load migration rules.',error:true}); }
    finally { setLoading(false); }
  }
  useEffect(()=>{load();},[]);
  function resetForm(){ const op=activeOperators[0]; setEditingId(''); setForm({...emptyForm,operatorId:op?.id||'',newPrefix:op?.newPrefix||''}); }
  function edit(rule:any){ setEditingId(rule.id); setForm({operatorId:rule.operatorId,ruleName:rule.ruleName,ruleType:rule.ruleType,prefixValue:rule.prefixValue||'',rangeFrom:rule.rangeFrom||'',rangeTo:rule.rangeTo||'',exactNumber:rule.exactNumber||'',newPrefix:rule.newPrefix,priority:rule.priority,status:rule.status,notes:rule.notes||''}); window.scrollTo({top:0,behavior:'smooth'}); }
  async function submit(e:FormEvent){ e.preventDefault(); setSaving(true); setMessage(null); try { const path=editingId?`/admin/migration-rules/${editingId}`:'/admin/migration-rules'; await api(path,{method:editingId?'PUT':'POST',body:JSON.stringify(payload(form))}); setMessage({text:editingId?'Rule updated. Publish rules to send this change to phones.':'Rule created. Test it, then publish rules.'}); resetForm(); await load(); } catch(err:any){setMessage({text:err.message||'Could not save rule.',error:true});} finally{setSaving(false);} }
  async function changeStatus(rule:any,statusValue:'active'|'inactive'){ setMessage(null); try{await api(`/admin/migration-rules/${rule.id}`,{method:'PUT',body:JSON.stringify({...payload({...rule,prefixValue:rule.prefixValue||'',rangeFrom:rule.rangeFrom||'',rangeTo:rule.rangeTo||'',exactNumber:rule.exactNumber||'',notes:rule.notes||''}),status:statusValue})}); setMessage({text:`Rule ${statusValue==='active'?'activated':'disabled'}. Publish rules to update phones.`}); await load();}catch(err:any){setMessage({text:err.message||'Could not change rule status.',error:true});}}
  async function publish(){setPublishing(true);setMessage(null);try{const r=await api<any>('/admin/migration-rules/publish',{method:'POST'});setMessage({text:`Published version ${r.data.versionNumber}. Mobile users can refresh and scan now.`});await load();}catch(err:any){setMessage({text:err.message||'Could not publish rules.',error:true});}finally{setPublishing(false);}}
  async function disableNonProduction(){setMessage(null);try{const r=await api<any>('/admin/migration-rules/disable-non-production',{method:'POST'});setMessage({text:r.data.disabledCount?`Disabled ${r.data.disabledCount} non-production rule${r.data.disabledCount===1?'':'s'}. Review your verified active rules, then publish.`:'No active demo/sample/fallback rules were found.'});await load();}catch(err:any){setMessage({text:err.message||'Could not disable non-production rules.',error:true});}}
  async function runTest(){setTesting(true);setTestResult(null);setMessage(null);try{const r=await api<any>('/admin/migration-rules/test',{method:'POST',body:JSON.stringify({oldNumber:test.replace(/\D/g,'')})});setTestResult(r.data);}catch(err:any){setMessage({text:err.message||'Rule test failed.',error:true});}finally{setTesting(false);}}
  const selectedOperator=operators.find((o)=>o.id===form.operatorId);
  return <>
    <div className="topbar"><div className="pageTitle"><h1>Migration Rules</h1><p>Create verified rules, test sample numbers, then publish the approved version to mobile devices.</p></div><button className="btn" disabled={publishing||!status?.activeRules} onClick={publish}>{publishing?'Publishing…':'Publish Active Rules'}</button></div>
    {message&&<p className={`notice ${message.error?'errorNotice':''}`} role="status">{message.text}</p>}
    <div className="grid ruleMetrics"><div className="metric"><span>Active drafts</span><strong>{status?.activeRules??0}</strong></div><div className="metric"><span>Inactive drafts</span><strong>{status?.inactiveRules??0}</strong></div><div className="metric"><span>Published version</span><strong>{status?.publishedVersion??'None'}</strong></div><div className="metric"><span>Published rules</span><strong>{status?.publishedRuleCount??0}</strong></div></div>
    {!activeOperators.length&&<p className="notice errorNotice">No active operator exists. Open Operators, create or activate an operator first.</p>}
    {status?.approvalIssues?.length>0&&<div className="card publishBlockers"><div className="row" style={{justifyContent:'space-between',alignItems:'flex-start'}}><div><h2>Publication blockers</h2><p>Fix or disable every item below. Draft rules cannot reach phones until this list is empty.</p></div><button className="btn danger" onClick={disableNonProduction}>Disable Demo Rules</button></div><ul>{status.approvalIssues.map((issue:string,index:number)=><li key={index}>{issue}</li>)}</ul></div>}
    <div className="card"><div className="row" style={{justifyContent:'space-between'}}><div><h2>{editingId?'Edit rule':'Create rule'}</h2><p>Use only official ranges. The new prefix is controlled by the selected operator.</p></div>{editingId&&<button type="button" className="btn secondary" onClick={resetForm}>Cancel edit</button>}</div>
      <form className="formGrid" onSubmit={submit}>
        <label>Operator<select required value={form.operatorId} onChange={e=>{const op=operators.find(o=>o.id===e.target.value);setForm({...form,operatorId:e.target.value,newPrefix:op?.newPrefix||''});}}><option value="">Select operator</option>{activeOperators.map(o=><option key={o.id} value={o.id}>{o.name} → {o.newPrefix}</option>)}</select></label>
        <label>Rule name<input className="input" required minLength={2} placeholder="e.g. Official QCell range 1" value={form.ruleName} onChange={e=>setForm({...form,ruleName:e.target.value})}/></label>
        <label>Rule type<select value={form.ruleType} onChange={e=>setForm({...form,ruleType:e.target.value as RuleType,prefixValue:'',rangeFrom:'',rangeTo:'',exactNumber:''})}><option value="prefix">Prefix</option><option value="range">7-digit range</option><option value="exact">Exact number</option><option value="exception">Exception</option></select></label>
        {(form.ruleType==='prefix'||form.ruleType==='exception')&&<label>Old-number prefix<input className="input" inputMode="numeric" maxLength={7} placeholder="1–7 digits" value={form.prefixValue} onChange={e=>setForm({...form,prefixValue:e.target.value.replace(/\D/g,'')})}/></label>}
        {(form.ruleType==='range'||form.ruleType==='exception')&&<><label>Range from<input className="input" inputMode="numeric" maxLength={7} placeholder="7 digits" value={form.rangeFrom} onChange={e=>setForm({...form,rangeFrom:e.target.value.replace(/\D/g,'')})}/></label><label>Range to<input className="input" inputMode="numeric" maxLength={7} placeholder="7 digits" value={form.rangeTo} onChange={e=>setForm({...form,rangeTo:e.target.value.replace(/\D/g,'')})}/></label></>}
        {(form.ruleType==='exact'||form.ruleType==='exception')&&<label>Exact old number<input className="input" inputMode="numeric" maxLength={7} placeholder="7 digits" value={form.exactNumber} onChange={e=>setForm({...form,exactNumber:e.target.value.replace(/\D/g,'')})}/></label>}
        <label>New prefix<input className="input" value={selectedOperator?.newPrefix||form.newPrefix} readOnly aria-readonly="true"/></label>
        <label>Priority<input className="input" required type="number" min="0" max="100000" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}/></label>
        <label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as any})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label>
        <label className="wideField">Notes<textarea className="input" rows={3} placeholder="Official source or approval note. Do not use ‘demo’, ‘sample’ or ‘fallback’ on publishable rules." value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>
        <button className="btn" disabled={saving||!activeOperators.length}>{saving?'Saving…':editingId?'Update Rule':'Create Rule'}</button>
      </form>
    </div>
    <div className="card"><h2>Test active draft rules</h2><p>Enter one old 7-digit number. A successful test must return <strong>matched: true</strong> and the correct 9-digit number.</p><div className="row"><input className="input" inputMode="numeric" maxLength={7} style={{maxWidth:280}} value={test} onChange={e=>setTest(e.target.value.replace(/\D/g,''))}/><button className="btn secondary" disabled={testing||test.length!==7} onClick={runTest}>{testing?'Testing…':'Test Number'}</button></div>{testResult&&<div className={`ruleTestResult ${testResult.matched?'successResult':'failedResult'}`}><strong>{testResult.matched?'Matched safely':'No safe match'}</strong><span>{testResult.matched?`${test} → ${testResult.migratedNumber} (${testResult.operatorName})`:testResult.reason}</span></div>}</div>
    <div className="card"><div className="row" style={{justifyContent:'space-between'}}><div><h2>Draft rules</h2><p>{loading?'Loading…':`${rules.length} rule${rules.length===1?'':'s'}. Changes stay in draft until Publish Active Rules is pressed.`}</p></div><button className="btn secondary" onClick={load} disabled={loading}>Refresh</button></div>
      {!loading&&!rules.length?<p className="notice">No rules exist. Create the first verified official rule above.</p>:<div className="tableWrap"><table><thead><tr><th>Name</th><th>Operator</th><th>Type / value</th><th>New prefix</th><th>Priority</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rules.map(r=><tr key={r.id}><td><strong>{r.ruleName}</strong>{r.notes&&<small className="cellNote">{r.notes}</small>}</td><td>{r.operatorName}</td><td>{r.ruleType}<small className="cellNote">{valueFor(r)}</small></td><td>{r.newPrefix}</td><td>{r.priority}</td><td><span className={`badge ${r.status==='inactive'?'inactiveBadge':''}`}>{r.status}</span></td><td><div className="row actionRow"><button className="btn secondary" onClick={()=>edit(r)}>Edit</button>{r.status==='active'?<button className="btn danger" onClick={()=>changeStatus(r,'inactive')}>Disable</button>:<button className="btn" onClick={()=>changeStatus(r,'active')}>Activate</button>}</div></td></tr>)}</tbody></table></div>}
    </div>
  </>;
}
